version: '3.7'

services:
  goodbuy-vue-app:
    container_name: goodbuy-vue-app
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/goodbuy-vue-docker'
      - '/goodbuy-vue-docker/node_modules'
    ports:
      - '8080:8080'
